/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/seed.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Seed (props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/seed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Light" position={[-1.437, 0.468, 0.686]} rotation={[-1.532, -0.841, -1.572]} scale={16.711} />
        <group name="Light001" position={[2.329, 0.534, -0.523]} rotation={[-1.722, 1.213, -1.725]} scale={144.807} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Stylized Wood.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/seed.glb')
