/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/tree.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tree.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tree_final.geometry} material={materials['Waxy Realistic Stylized bark']} />
      <mesh geometry={nodes.Plane1228.geometry} material={materials['leaf.001']} position={[1.611, 3.605, -0.807]} rotation={[-1.39, 0.161, -1.289]} scale={0.142} />
    </group>
  )
}

useGLTF.preload('/tree.glb')
